(function() {  
    tinymce.create('tinymce.plugins.tweet_dis', {  
        init : function(ed, url) {  
            ed.addButton('tweet_dis', {  
                title : 'Tweet',  
                image : url+'/../images/image_dis.png',
                onclick : function() {  
                     ed.selection.setContent('[tweet_dis]' + ed.selection.getContent() + '[/tweet_dis]');  
  
                }  
            });
            ed.addButton('tweet_box', {
                title : 'Tweet',
                image : url+'/../images/image.png',
                onclick : function() {
                    ed.selection.setContent('[tweet_box]' + ed.selection.getContent() + '[/tweet_box]');

                }
            });
        },  
        createControl : function(n, cm) {  
            return null;  
        }  
    });  
    tinymce.PluginManager.add('tweet_dis', tinymce.plugins.tweet_dis);
    tinymce.PluginManager.add('tweet_box', tinymce.plugins.tweet_dis);
})();